Draft of Drizly post
dagster-io/dagster-website pull request #44
Opened 2021-03-02 17:02 UTC by mgasner

2021-03-02 17:18 UTC, dehume-drizly approved these changes

2021-03-03 03:11 UTC, schrockn commented on pages/blog/shared-spaces-at-drizly.mdx
> +<table style={{border: "1px solid"}}>
I would love to fill out this table more. 

Example additional columns: "Feedback Time" "Errors Caught"

I'd love to fit this table into this framework:

![Screen Shot 2021-03-02 at 8 10 17 PM](https://user-images.githubusercontent.com/28738937/109746882-5caa3680-7b93-11eb-8b13-9b4014fcc551.png)

![Screen Shot 2021-03-02 at 8 10 23 PM](https://user-images.githubusercontent.com/28738937/109746899-6764cb80-7b93-11eb-8321-7e49f236d0ea.png)

2021-03-03 03:12 UTC, schrockn commented on pages/blog/shared-spaces-at-drizly.mdx
> +Finally, when a user is ready to put out a PR, our CI runs final integration tests on our Dagster project in our AWS dev and prod accounts.
Just to hammer this home, it would be great to emphasize that Dagster uniquely provides the ability to do this in the world of python-driven data pipelines, and then to clearly state the value "Our stakeholders are much more productive in this environment"

2021-03-03 03:12 UTC, schrockn commented on pages/blog/shared-spaces-at-drizly.mdx
> +Our two AWS deployments (dev and prod) both take advantage of the Dagster ECS Launcher.
do they use the out-of-the-box ECS run launcher? or a custom one?

2021-03-03 03:16 UTC, schrockn requested changes
I think this is great overall. Thanks so much @dehume-drizly!

I would like to see a few changes where we in very clear terms state the value of this setup. The buildup describe all the different environments that are there is really compelling, but it is missing a conclusion where the value is clearly articulated or it is compared to other workflow managers/orchestrators

2021-03-03 10:13 UTC, dehume-drizly commented
Thanks for the feedback, I tired to flesh out a couple of sections (highlighted). For now seemed easier to do WIP changes in the goolge doc:

https://docs.google.com/document/d/1qkZPz_hzL0N0cRuyOJC9hwteX-_DFn_fuiT14IZXDmc/edit?pli=1#

2021-03-03 12:11 UTC, schrockn commented
Cool. I left some comments in the docs. I think the additions you made are great. @mgasner can you pull them in?

2021-03-03 21:54 UTC, mgasner commented on pages/blog/shared-spaces-at-drizly.mdx
> +Our two AWS deployments (dev and prod) both take advantage of the Dagster ECS Launcher.
there isn't an out of the box ECS run launcher -- but there's hope that this will get contributed back. we can note the status of this

2021-03-03 21:55 UTC, mgasner commented on pages/blog/shared-spaces-at-drizly.mdx
> +<table style={{border: "1px solid"}}>
Maybe we can add a paragraph about this immediately afterwards

2021-03-03 21:56 UTC, mgasner commented on pages/blog/shared-spaces-at-drizly.mdx
> +Finally, when a user is ready to put out a PR, our CI runs final integration tests on our Dagster project in our AWS dev and prod accounts.
I think we could add a few sentences to make this clearer

2021-03-03 22:19 UTC, dehume-drizly commented on pages/blog/shared-spaces-at-drizly.mdx
> +Our two AWS deployments (dev and prod) both take advantage of the Dagster ECS Launcher.
Added a note in the doc that the current launcher is custom

2021-03-03 22:20 UTC, dehume-drizly commented on pages/blog/shared-spaces-at-drizly.mdx
> +<table style={{border: "1px solid"}}>
I added something at the beginning of the "Standardized deployments for the entire development lifecycle" section to flesh this out

2021-03-03 22:24 UTC, schrockn commented
Did you do any custom things in the run launcher to integrate with your infrastructure? If so I think that is very interesting to note.

2021-03-04 12:16 UTC, dehume-drizly commented
> Did you do any custom things in the run launcher to integrate with your infrastructure? If so I think that is very interesting to note.

That run launcher is still very basic and more of a work in progress. I feel more confident in the overall structure of our deploys and mainly just wanted to call it out that you can configure different dagster instances across different deployments

2021-03-04 13:31 UTC, schrockn commented
Ok got it. This looks great to me! @mgasner can you make sure and incorporate Dennis' changes and then let's ship this.

2021-03-15 17:26 UTC, merged