Draft of Mapbox post
dagster-io/dagster-website pull request #60
Opened 2021-05-13 23:29 UTC by mgasner

2021-05-14 10:17 UTC, Benyuel commented on pages/blog/incremental-adoption-mapbox.mdx
> +Dagster pipelines them into Airflow DAGs that can be deployed on our existing
```suggestion
Dagster pipelines into Airflow DAGs that can be deployed on our existing
```

2021-05-14 10:18 UTC, Benyuel commented on pages/blog/incremental-adoption-mapbox.mdx
> +interoperate with legacy Airflow tasks and DAGs. (If we starting from scratch,
```suggestion
interoperate with legacy Airflow tasks and DAGs. (If we were starting from scratch,
```

2021-05-18 15:38 UTC, schrockn requested changes
Really great overall. I think the code examples ended up in a nice spot. I have a couple comments but really excited to ship this.

2021-05-18 15:38 UTC, schrockn commented on pages/blog/incremental-adoption-mapbox.mdx
> +needed with our legacy Airflow systems.
So I think we nee to expand on this a bit so that folks aren't confused. 

"Dagster can serve as a total replacement for Airflow. However, we had significant investments in Airflow and infrastructure around Airflow, and we wanted to retain that investment while taking advantage of Dagster's APIs and developer experience. Luckily, Dagster is flexible enough to operate on top of Airflow. Dagster comes with a built-in Airflow integration to assist with both incremental adoption on top of Airflow as well as migration away from Airflow. While we can't take advantage of all of Dagster's features, it does allow a dramatically better dev and test workflow. As a result, we've adopted Dagster without massive infrastructure and while working alongside teams that use vanilla Airlfow. "

Maybe even link to the Dagster v Airflow article in the first sentence

The above is not perfect by any stretch but a bad outcome would be to re-introduce confusion around our relationship with Airflow, which I think this paragraph does.

2021-05-18 15:38 UTC, schrockn commented on pages/blog/incremental-adoption-mapbox.mdx
> +interoperate with legacy Airflow tasks and DAGs. (If we starting from scratch,
if we were starting

2021-05-18 15:38 UTC, schrockn commented on pages/blog/incremental-adoption-mapbox.mdx
> +for incremental testing and a tight dev cycle.
I think this section is missing a conclusion. The step launcher is a really powerful capability and is at the heart of why this is useful. Explaining it is worth a sentence and probably even a chart?

Like a simplified version of this:

<img width="905" alt="Screen Shot 2021-05-18 at 8 34 27 AM" src="https://user-images.githubusercontent.com/28738937/118680803-e55c6a00-b7b3-11eb-92e4-473256b3cbc5.png">

The solid is pure pyspark code, and the step launcher controls *where* the pyspark code executes. The pyspark code does not change between the environments.

2021-05-18 15:38 UTC, schrockn commented on pages/blog/incremental-adoption-mapbox.mdx
> +This has made a huge difference for developer productivity. Just to give a sense
love this paragraph

2021-05-18 15:38 UTC, schrockn commented on pages/blog/incremental-adoption-mapbox.mdx
> +production infrastructure. As a consequence, tests are much less costly, because
still would love even a "back of the napkin" estimate of cost reduction. any number, either absolute or relative, would lend this much more credibility

2021-05-18 15:39 UTC, schrockn commented on components/editors.json
> +      "id": "Ben_Pleasanton",
This is a problem in our blog generally but we should list company/title along with name in our bylines

2021-05-18 15:51 UTC, Benyuel commented on pages/blog/incremental-adoption-mapbox.mdx
> +production infrastructure. As a consequence, tests are much less costly, because
My gut estimate is that we saved over 50% of what our development cost would have been since these dagster pipelines were developed locally prior to testing in a staging environment on AWS.    

I remember initially in the first few weeks our engineering manager questioning why this new project was not showing on our cost reporting score cards even though the project was well underway.  It was due to easy local development with dagster.

2021-05-18 15:53 UTC, Benyuel commented on pages/blog/incremental-adoption-mapbox.mdx
> +for incremental testing and a tight dev cycle.
Our step launcher in our pipelines is currently a somewhat similar but forked version of the dagster EMR step launcher.  The modifications we put in place were to handle packaged airflow dags and dependencies when that step launcher executes from the airflow orchestrator.  Our EMR step launcher also creates ephemeral EMR clusters instead of submitting to a singular externally managed EMR cluster.

2021-05-19 22:45 UTC, mgasner commented on pages/blog/incremental-adoption-mapbox.mdx
> +needed with our legacy Airflow systems.
yeah, i think cutting this para and slightly fleshing/reworking the airflow stuff later is the best approach.

2021-05-19 22:51 UTC, mgasner commented on components/editors.json
> +      "id": "Ben_Pleasanton",
yeah, we need to revamp a couple of things about the blog display -- will open a tracking issue

2021-05-19 23:05 UTC, sryza approved these changes
I think this looks great.  Excited for it to go out.

2021-05-19 23:07 UTC, merged