approachability blog post
dagster-io/dagster-website pull request #63
Opened 2021-05-24 21:34 UTC by sryza

2021-05-24 21:57 UTC, schrockn requested changes
Couple suggestions. Just doing queue management.

2021-05-24 21:57 UTC, schrockn commented on pages/blog/approachability.mdx
> +For a developer-focused product, APIs are the user interface. Users tell us a lot of nice things about the expressivity of Dagster’s APIs, but one of the more persistent pieces of critical feedback t
might want to emphasize learning curve rather than heaviness

2021-05-24 21:57 UTC, schrockn commented on pages/blog/approachability.mdx
> +Many of the changes are aimed at improving Dagster’s *progressive disclosure of complexity.*  Dagster includes a large array of concepts that help model and organize the complexity of the data develo
Let's avoid calling it "complex software" and phrases like "all these abstractions". I would suggest the "grows with you" language.

"You want software that grows with you to support complex data applications. But at the same time a simple task––such as getting a basic pipeline up and running––should be simple."

2021-05-24 23:58 UTC, sryza commented on pages/blog/approachability.mdx
> +Many of the changes are aimed at improving Dagster’s *progressive disclosure of complexity.*  Dagster includes a large array of concepts that help model and organize the complexity of the data develo
👍

2021-05-24 23:58 UTC, sryza commented on pages/blog/approachability.mdx
> +For a developer-focused product, APIs are the user interface. Users tell us a lot of nice things about the expressivity of Dagster’s APIs, but one of the more persistent pieces of critical feedback t
👍

2021-05-25 00:36 UTC, schrockn approved these changes
Made some additional comment on the config section. Would love to see them addressed but your discretion. I think this is great.

2021-05-25 00:36 UTC, schrockn commented on pages/blog/approachability.mdx
> +Many of the changes are aimed at improving Dagster’s *progressive disclosure of complexity.*  Dagster includes a large array of concepts that help model and organize the complexity of the data develo
Ah this is great. Your version better than mine

2021-05-25 00:36 UTC, schrockn commented on pages/blog/approachability.mdx
> +We’ve made it so that you don’t need to deal with config schema system to supply config to a solid.
Hmmm so re-reading this reads a bit off too. "deal with" reads super negative.

"We've made it so that config schema is purely opt-in. Now, by default, solids can accept *any* config, and you can opt-in to specifying schema."

2021-05-25 00:36 UTC, schrockn commented on pages/blog/approachability.mdx
> +We observed that, for many people, this was a lot to deal with when learning the system.  In order to do basic things, they needed to understand how config schemas worked and the type system for conf
Not sure you want to get into, but you could always just provide `dict` to config_schema. We just didn't document it or encourage it.

2021-05-25 00:36 UTC, schrockn commented on pages/blog/approachability.mdx
> +So we made a small but significant change, which is to make the default config schema type the `Any` type. What this essentially means is that now you can provide *config* to a solid without needing
It might be interesting to note that it was always gradually typed like this, but might not be worth getting into it

2021-05-25 15:03 UTC, sryza commented on pages/blog/approachability.mdx
> +We’ve made it so that you don’t need to deal with config schema system to supply config to a solid.
I like yours better.  Will change.

2021-05-25 16:03 UTC, merged