crag blog post
dagster-io/dagster-website pull request #78
Opened 2021-08-03 22:52 UTC by sryza

This incorporates both Nick and Owen's comments.  It also adds a section on the Dagit left nav change.  I think it would be cool to do another post on how CRAG enables longitudinal views over step execution time when we have that.

2021-08-04 15:36 UTC, schrockn commented
Would be very nice to be able to review this on the deployed vercel

2021-08-04 16:34 UTC, sryza commented
Now successfully deployed:
https://dagster-website-git-crag-post-elementl.vercel.app/blog/core-apis-moving-towards-1-0

On Wed, Aug 4, 2021 at 8:36 AM Nicholas Schrock ***@***.***>
wrote:

> Would be very nice to be able to review this on the deployed vercel
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/dagster-io/dagster-website/pull/78#issuecomment-892760762>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAE74B4XLCISFPNMOIZQUS3T3FM7TANCNFSM5BPYXGXQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&utm_campaign=notification-email>
> .
>

2021-08-05 16:47 UTC, OwenKephart requested changes

2021-08-05 16:47 UTC, OwenKephart commented on pages/blog/core-apis-moving-towards-1-0.mdx
> +    return int(arg1)`
nit: extra tick mark at the end

2021-08-05 16:47 UTC, OwenKephart commented on pages/blog/core-apis-moving-towards-1-0.mdx
> +<img src="/posts/core-apis-moving-towards-1-0/pipeline_diagram.png" />
I think these images should be paired with some text that explains them, as it's a bit heavy to digest all at once. I'm imagining a structure somewhat like:

"Currently, pipelines encapsulate a large number of independent concepts. In addition to defining the logical structure of dependencies, a pipeline must also enumerate all of possible modes it could be run in, with each mode in turn enumerating all of the required resources, potentially paired with multiple presets per mode.

< picture of pipeline stuff >

In contrast, the new APIs allow the dependency structure (now called a _Graph_) to be separated from the definition of the resources that it might be used with. _Jobs_ are executable specializations of graphs. A job binds a graph to a set of resources and default configuration or a set of partitions. Each schedule or sensor targets a job. You can create multiple jobs from the same graph, e.g. a dev job and a prod job. If, previously, you had a pipeline with three modes, you’d likely now have three jobs that all reference the same graph.

<picture of job stuff>"

2021-08-05 16:47 UTC, OwenKephart commented on pages/blog/core-apis-moving-towards-1-0.mdx
> +    return [do_it_all.to_job(resource_defs={"external_service": prod_external_service})]
nit: On small screens (potentially all screens?) this gets cut off, and requires sideways scrolling to see the whole thing. Might make sense to break it into different lines.

2021-08-05 16:47 UTC, OwenKephart commented on pages/blog/core-apis-moving-towards-1-0.mdx
> +do_it_all_schedule = ScheduleDefinition(cron_schedule="0 0 * * *", job=do_it_all)
nit: this also requires sideways scrolling to see.

2021-08-09 17:33 UTC, sryza commented on pages/blog/core-apis-moving-towards-1-0.mdx
> +<img src="/posts/core-apis-moving-towards-1-0/pipeline_diagram.png" />
Great point.  I am going to lift copy what you wrote almost verbatim.

2021-08-10 17:32 UTC, merged